[package]
name = "p2"
version = "0.1.0"
authors = ["Arunscape <arun@woosaree.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
